### ISSUE TITLE
Create a base HTML template for use in flask

### ISSUE THREAD

**Issue by zbreit** [team-pass/FIDO-login#22]
Rather than duplicating a lot of our code for forms and such, we should just create a base template (i.e., a `base.html` file) that gets included in all webpages (see https://flask.palletsprojects.com/en/1.1.x/tutorial/templates/?highlight=templating).

**Comment by SamuelHoward** [comment]
I am working on this along with @Menolikepie (Balaji). Here is the relevant draft pull request #29

**Comment by zbreit** [comment]
This was closed in #29
